from playwright.sync_api import sync_playwright
import os, urllib.parse
R=[]; ok=lambda n,c: R.append((n,bool(c)))
with sync_playwright() as p:
    b=p.chromium.launch(); pg=b.new_page(viewport={"width":1280,"height":820}); pg.add_init_script("window.open=(u)=>{window.__o=u}")
    pg.goto("file://"+os.path.abspath(os.path.join(os.path.dirname(__file__),"udhaar.html")))
    ok("empty state", "Abhi koi entry nahi" in pg.inner_text("#list"))
    def add(n,ph,a,t="out"):
        pg.fill("#name",n); pg.fill("#phone",ph); pg.fill("#amt",str(a)); pg.select_option("#type",t); pg.click("button.add")
    add("Ramesh ji","9800000011",1200); add("Sunita ji","9800000012",640); add("Ramesh ji","9800000011",650); add("Anil bhai","9800000013",300)
    ok("3 people (same phone merges)", pg.locator(".row").count()==3)
    ok("sorted by balance", pg.locator(".nm").all_inner_texts()==["Ramesh ji","Sunita ji","Anil bhai"])
    ok("balance adds up 1850", "₹1,850 baaki" in pg.locator(".row").nth(0).inner_text())
    ok("counters", [pg.inner_text(x) for x in ("#sTot","#sPpl","#sOut","#sIn")]==["₹2,790","3","₹2,790","₹0"])
    pg.locator(".row").nth(0).locator("[data-a=wa]").click(); u=urllib.parse.unquote(pg.evaluate("window.__o"))
    ok("whatsapp number+name+amount", u.startswith("https://wa.me/919800000011?text=") and "Ramesh ji" in u and "₹1,850" in u)
    ok("reminder mark", "Yaad dilaya" in pg.locator(".row").nth(0).inner_text())
    pg.locator(".row").nth(2).locator("[data-a=pay]").click()
    ok("pay prefills form", pg.input_value("#name")=="Anil bhai" and pg.input_value("#type")=="in")
    pg.fill("#amt","300"); pg.click("button.add")
    ok("cleared shows Hisaab saaf, no whatsapp button", "Hisaab saaf" in pg.locator(".row").nth(2).inner_text() and pg.locator(".row").nth(2).locator("[data-a=wa]").count()==0)
    ok("counters after payment", [pg.inner_text(x) for x in ("#sTot","#sPpl","#sIn")]==["₹2,490","2","₹300"])
    pg.reload(); ok("survives reload", pg.locator(".row").count()==3)
    with pg.expect_download() as dl: pg.click("#csv")
    ok("csv 1+5 rows", len(open(dl.value.path(),encoding="utf-8-sig").read().strip().splitlines())==6)
    pg.fill("#name","X"); pg.fill("#phone","12"); pg.fill("#amt","5"); pg.click("button.add"); ok("bad phone rejected", pg.locator(".row").count()==3)
    b.close()
for n,c in R: print("PASS" if c else "FAIL",n)
print(sum(c for _,c in R),"/",len(R))
